kind: Service
apiVersion: v1
metadata:
  name: tripviewer-subdomain
  namespace: web
  labels:
    app: tripviewer-deployment
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: tripviewer
  type: ClusterIP
