kind: Deployment
apiVersion: apps/v1
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripviewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: 'registrylzk2091.azurecr.io/tripviewer:1.0'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: USERPROFILE_API_ENDPOINT
              value: http://userprofile-subdomain.api.svc.cluster.local
            - name: TRIPS_API_ENDPOINT
              value: http://trips-subdomain.api.svc.cluster.local