kind: Service
apiVersion: v1
metadata:
  name: trips-subdomain
  namespace: api
  labels:
    app: trips-deployment
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: trips
  type: ClusterIP