apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    app: poi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: registrylzk2091.azurecr.io/poi:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: SQL_USER
              value: sqladminlZk2091
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: password
            - name: SQL_SERVER
              value: sqlserverlzk2091.database.windows.net
            - name: SQL_DBNAME
              value: mydrivingDB