apiVersion: v1
kind: Service
metadata:
  name: userprofile-subdomain
spec:
  selector:
    app: userprofile
  ports:
    - name: userprofile-ports # Actually, no port is needed.
      port: 80
      targetPort: 8080
