kind: Service
apiVersion: v1
metadata:
  name: userprofile-subdomain
  namespace: api
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: userprofile
  type: ClusterIP