apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tripinsight-ingress
  namespace: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: tripviewer-subdomain
              servicePort: 80
            path: /
#          - backend:
#              serviceName: aks-helloworld-two
#              servicePort: 80
#            path: /hello-world-two(/|$)(.*)
#          - backend:
#              serviceName: aks-helloworld-one
#              servicePort: 80
#            path: /(.*)
